### ISSUE TITLE
Possible permission issue

### ISSUE THREAD

**Issue by stof** [liip/LiipHyphenatorBundle#2]
The Hyphenator library needs to be able to write some files on the disk in the place where it is installed. This should be documented as the vendor dir may not be writable (a clean solution would be to patch the library to make the path configurable and then use the Symfony2 cache folder)

**Comment by lsmith77** [comment]
see https://github.com/liip/LiipHyphenatorBundle/pull/13

**Comment by lsmith77** [comment]
@heiglandreas ``Org_Heigl_Hyphenator::setDefaultParseFileDir()`` doesn't seem to exist anymore .. from reading the code I am not sure if the directory into which files are written can be separated from the directory from where the ini files are read .. can you give me a hint here?

**Comment by lsmith77** [comment]
ah it seems like you simply now provide the files pre-parsed and so this issue is solved without any further input: https://github.com/heiglandreas/Org_Heigl_Hyphenator/commit/4404fd24629be1a8ca7ab29f0a129e0da8854353
