### ISSUE TITLE
Support internationalization

### ISSUE THREAD

**Issue by stof** [liip/LiipHyphenatorBundle#3]
Currently, the language is set in the configuration and cannot be changed. This does not allow to support internationalized websites.
Note that this will require a big change in the way the bundle works.

**Comment by lsmith77** [comment]
@heiglandreas I am finally looking into this. the lib has a "default locale" option, so that makes me wonder if I can have multiple languages active at once and if I can dynamically pass in the language to use but it looks like the ``hyphenate()`` method has no locale parameter.

**Comment by lsmith77** [comment]
ideally I guess I would also like to lazily add dictionaries @heiglandreas

```
public function hyphenate ( $string, $locale = null)
```

would then use the default locale if no locale is passed in.
if a locale is passed it, it would check if the dictionary was already added and if not add it.

is this already possible?

**Comment by heiglandreas** [comment]
At the moment you can use different hyphenator-instances for different locales like this:

```php 
$hyphenatorA = Org\Heigl\Hyphenator\Hyphenator::factory($pathToConfigFile, $localeA);
$hyphenatorB = Org\Heigl\Hyphenator\Hyphenator::factory($pathToConfigFile, $localeB);

echo $hyphenatorA->hyphenate($string);
echo $hyphenatorB->hyphenate($string);
```

I'm not sure I would want to have one hyphenator-instance ruling all the locales... Witzhout having dug into it very far it seems it would add a lot of overhead for edge cases. As normally you would hyphenate a string only with one hyphenation-pattern. Either the text shall be hyphenated using swiss hyphenation patterns or german hyphenation patterns. But rarely using both patterns...

If that doesn't fit your needs, I'll think up some way to allow such a hyphenation ;) 

I could think of a ```HyphenationManager``` that combines different Hyphenator-Instances and implements the ```hyphenate```- method like your example shows and internally delegates to the correct hyphenator-instance.

**Comment by lsmith77** [comment]
makes sense.

**Comment by heiglandreas** [comment]
Does that help you? Or is there any way I can help you further?

**Comment by lsmith77** [comment]
no I think I will follow this approach and add a custom factory to the Bundle for now

**Comment by lsmith77** [comment]
see https://github.com/liip/LiipHyphenatorBundle/pull/13
